model_path:
  small: "models/mistral-7b-instruct-v0.1.Q3_K_M.gguf"
  large: "models/mistral-7b-instruct-v0.1.Q5_K_M.gguf"

model_type: "mistral"

embeddings:
  model_name: "BAAI/bge-large-en-v1.5"
  model_kwargs: {
   "device" : "cpu",
  }
  encode_kwargs: {
    "normalize_embeddings": True
  }

model_config: {
  'max_new_tokens': 512, 
  'temperature': 0, 
  'context_length': 4096, 
  'gpu_layers': 0
}

chat_history_path: "./chat_sessions/"